import { ImageResponse } from "next/og";

// OG share card for NEON CURATOR — generated by Next at the edge.
export const alt = "NEON CURATOR — Discover & Track Anime";
export const size = { width: 1200, height: 630 };
export const contentType = "image/png";

export default function OpengraphImage() {
  return new ImageResponse(
    (
      <div
        style={{
          width: "100%",
          height: "100%",
          display: "flex",
          flexDirection: "column",
          alignItems: "center",
          justifyContent: "center",
          background: "#0f172a",
          fontFamily: "sans-serif",
        }}
      >
        <div style={{ display: "flex", fontSize: 84, fontWeight: 800 }}>
          <span style={{ color: "#60a5fa" }}>NEON</span>
          <span style={{ color: "#ffffff" }}>&nbsp;CURATOR</span>
        </div>
        <div
          style={{
            marginTop: 24,
            fontSize: 34,
            color: "#94a3b8",
            maxWidth: 880,
            textAlign: "center",
          }}
        >
          Discover anime, filter-first. 15,000+ titles, one query.
        </div>
        <div
          style={{
            marginTop: 40,
            display: "flex",
            gap: 16,
          }}
        >
          {["Filters", "Watchlist", "Stats"].map((tag) => (
            <div
              key={tag}
              style={{
                display: "flex",
                padding: "8px 22px",
                borderRadius: 6,
                border: "1px solid #1e293b",
                background: "#1e293b",
                color: "#cbd5e1",
                fontSize: 24,
              }}
            >
              {tag}
            </div>
          ))}
        </div>
      </div>
    ),
    { ...size },
  );
}
